backend/package.json
backend/src/app.module.ts
backend/src/config/datasource.ts
backend/src/config/swagger.ts
backend/src/main.ts

- api/docs 경로에서 swagger 경로 확인가능
- swagger.ts, datasource.ts 경로를 config/ 로 옮김

27 swagger 설치 및 세팅

---

frontend/src/components/game/ScoreBoard.tsx
frontend/src/components/game/status/Run.tsx

1. canvas 를 180° rotate
2. 내부 score canvas 를 다시 180° rotate
3. ???
4. profit!!!

35 css rotate

---

frontend/src/components/game/status/Run.tsx
frontend/src/matterEngine/matterJsSet.ts
frontend/src/matterEngine/matterJsUnit.ts
frontend/src/matterEngine/player.ts

paddle 밖으로 나가는건 수정하지 못함 
Run.tsx 수정하고 나서 해결할 예정

34 sensorpaddle fix

---

backend/src/channel/channel.service.ts
backend/src/type/channel.ts
frontend/src/components/button/MakeChannelButton.tsx
frontend/src/components/chat/MakeChannel.tsx
frontend/src/pages/channel/list.tsx
frontend/src/pages/channel/message-channel-list.tsx
frontend/src/pages/channel/public-channel-list.tsx
frontend/src/type.ts

풀리퀘, 커밋을 작은단위로 만들라는 가르침을 받고 작게 만들었습니다.
채널리스트, 공개방 목록, 대화방 목록에 UI를 완전히 만들기 전에 
UI의 위치와 레이아웃을 대강 만들었습니다.
https://github.com/pong-nyan/pong-nyan/assets/26201797/2dfaf825-b946-4483-a552-ffa8e9f0ba9c
다음 브랜치에서 UI를 보강하면서 기능을 구현하겠습니다.

36 chat channel UI

---

frontend/src/components/game/status/Run.tsx
frontend/src/context/socketGameEvent.ts
frontend/src/type.ts

Run.tsx 의 socket 이벤트들을 분리했습니다
이제 200줄 로 줄어듦!

39 game socket event 분리

---

frontend/src/components/game/status/Run.tsx
frontend/src/matterEngine/player.ts

- 이제 플레이어가 밖으로 안나감
- left right 방향 주의
(방향은 불편하신 분이 바꾸주시면 대단히 감사를 표하겠습니다...)

feat(game): fix player Outboundary

---

backend/src/game/game.gateway.ts
frontend/src/components/game/status/Run.tsx
frontend/src/context/socketGameEvent.ts
frontend/src/matterEngine/matterJsUnit.ts
frontend/src/matterEngine/player.ts

- socketOnXXXX 를 useEffect안으로 옮김
- 와치 되는 상황에서 코드 수정 후  게임 실행했을 때 소켓 여러 번 가지는 이슈가 있는 듯

feat(game): socket on 여러 번 받는 문제 해결(핫 리로딩 문제 추측)

---

frontend/src/components/game/status/Run.tsx

fix: css update before game start

---

frontend/src/pages/channel/list.tsx

fix(chat): fix list.tsx

---

backend/src/game/game.gateway.ts
backend/src/game/game.service.ts
frontend/src/components/game/ScoreBoard.tsx
frontend/src/components/game/status/Run.tsx
frontend/src/context/socketGameEvent.ts
frontend/src/matterEngine/matterJsGameEvent.ts
frontend/src/matterEngine/matterJsSet.ts
frontend/src/matterEngine/matterJsUnit.ts
frontend/src/type.ts

- Score Sever 이벤트 관리 추가
- sensor 닿으면 게임 일시정지됨
- countdown 보여주는 화면은 다른 이슈에서 구현할 예정
- Ball에 대한 방향 좌표계 정의(`setStartBall` 함수 안에 있음)
- 게임 시작하면서 지정한 각도로 볼 보낼 수 있음(각도 제한해서 랜덤 괜찮을 듯?)

54 score+countdown

---

backend/src/channel/channel.gateway.ts
backend/src/channel/channel.service.ts
backend/src/type/channel.ts
frontend/src/components/chat/ChannelList.tsx
frontend/src/components/chat/MakeChannel.tsx
frontend/src/type.ts

- 공개방 만들기
- 비밀번호방 만들기
- 해당 방 관련 자료구조, 
- 초대전용방
- 최대인원
- 처음 들어왔을때 방 목록 띄우기
https://github.com/pong-nyan/pong-nyan/assets/26201797/2d372c41-f248-47ac-87a4-c10036c2c18c

58 make channel according to conditions

---

frontend/src/components/button/NavButtonWrapper.tsx
frontend/src/pages/channel/list.tsx
frontend/src/styles/NavButtonWrapper.module.css

- 프론트에서 game페이지로 이동시 자기 자신과 게임할 수 있는 버그가 생김.

65 버튼 리다이렉션 붙이기

---

backend/src/channel/channel.gateway.ts
frontend/src/components/chat/ChannelList.tsx

제곧내
https://github.com/pong-nyan/pong-nyan/assets/26201797/2d9c6f0e-ec72-4886-92a4-8664900fe9dc
```jsx
useEffect(() => {
socket.emit('chat-request-channel-list');
```

feat(chat): channel/list 접속시 방목록 업데이트

---

frontend/src/pages/_document.tsx

fix: /를 더해서 올바른 경로로 따라가게 수정

---

Makefile
backend/src/game/game.gateway.ts
backend/src/game/game.guard.spec.ts
backend/src/game/game.guard.ts
backend/src/game/game.module.ts
backend/src/game/interface/game.interface.ts
frontend/src/auth/components/FortyTwoIntraSignInButton.tsx
frontend/src/pages/auth/index.tsx

백엔드에서 game gateway 로 들어오는 소켓 이벤트 guard
GameGuard 제작해서 game gateway 전체에 적용
로그인 안하면 게임 시작 못합니다

93 game guard 구현

---

frontend/src/chat/components/MakeChannel.tsx
frontend/src/chat/components/MakeChannelButton.tsx
frontend/src/chat/styles/MakeChannel.module.css
frontend/src/chat/styles/NavButtonWrapper.module.css
frontend/src/pages/channel/list.tsx
frontend/src/styles/globals.css

+버튼 == MakeChannelButton 위치조정
700px이하 화면에서 레이아웃 반응형으로 감싸기 
비밀번호 입력 <input> 필요할때만 보이게 설정
https://github.com/pong-nyan/pong-nyan/assets/26201797/018e2979-f62c-445b-a954-c3cb6e4a077a

101 plus button location set

---

.vscode/settings.json
frontend/src/pages/rank/index.tsx
frontend/src/rank/components/RankUser.tsx
frontend/src/rank/components/RankUserList.tsx
frontend/src/rank/rankType.ts
frontend/src/rank/styles/Rank.module.css

랭킹 페이지 가데이터를 이용해서 심플하게 만듦.
->
추후 백과 연동 필요함.
```ts
const RankUserList = ({ rankUserList } : RankUserListProps) => {
return (
<div className={styles.rankUserList}>
<RankUserColumn />
{rankUserList.map((rankUser) => (
<RankUser key={rankUser.nickname} rankUser={rankUser} />
))}
</div>
);
};
```

81 랭킹 페이지 만들기

---

frontend/src/chat/components/MakeChannel.tsx
frontend/src/chat/components/Modal.tsx
frontend/src/pages/channel/list.tsx
frontend/src/styles/globals.css

- 모달창 만듬
- 비밀번호 유효성검사
https://github.com/pong-nyan/pong-nyan/assets/26201797/510869b2-e0d9-45f5-9ecb-02ca7834f517
- 방만들면 만들었다고 알려주기

feat(chat): makeChannel modal

---

backend/src/game/game.gateway.ts
backend/src/game/game.service.ts
frontend/src/context/socketGameEvent.ts
frontend/src/game/components/Run.tsx
frontend/src/game/logic/resumeGame.ts
frontend/src/game/matterEngine/matterJsGameEvent.ts

- score 업데이트 문제 useEffect 분리로 해결
- 게임시작되면 카운트다운 적용되게 함
- score 업데이트 되면 emit함
- winnerNickname의 여부로 게임에 문제가 있는 지 판단함
- useEffect의 종속 배열을 고려해서 훅을 사용해야 함
- jimin님과 머리 맞대서 해결 ㅎㅎ..

111 score logic 보완

---

backend/src/main.ts
frontend/src/auth/logic/encodeFileToBase65.ts
frontend/src/pages/auth/signup.tsx
nginx/nginx.conf

회원가입시 base64 encode해서 이모지 업로드함
```ts
<input
type="file"
id="image"
accept='image/*'
onChange={async(e) => {
if (!e.target.files) return;
const file = e.target.files[0];
if (!file) return;
const image = await encodeFileToBase64(file);
setAvatar(image);
}}
onClick={(e) => e.currentTarget.value = ''}
/>
```
[base64 사용하는 법](https://velog.io/@byeol4001/Base-64%EC%99%80-base64-img-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0) 을 참고하여 프론트상에서 user의 아바타를 띄어주면 됩니다.
db에 잘 박히는거 확인함

feat(login): upload image

---

backend/src/channel/channel.controller.ts
backend/src/channel/channel.dto.ts
backend/src/channel/channel.gateway.ts
backend/src/channel/channel.guard.ts
backend/src/channel/channel.module.ts
backend/src/channel/channel.service.ts
backend/src/type/channel.ts
frontend/src/pages/channel/index.tsx
frontend/src/pages/channel/list.tsx
frontend/src/pages/channel/message-channel-list.tsx
frontend/src/pages/channel/public-channel-list.tsx

유저를 intraId를 기준으로 서로 분리하였습니다.
https://github.com/pong-nyan/pong-nyan/assets/26201797/e9663276-2afe-4233-92ea-4cb2b9777479
채널에 접속한 유저목록이 가끔 안 나오는데 이유는 모르겠습니다.
+ 뭔가 연동해야 되는걸 빼먹은 느낌인데 무엇을 빼먹었는지 여러분이 찾아주세요

114 seperated user in channel

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.dto.ts
backend/src/auth/auth.service.ts
frontend/src/auth/components/FortyTwoIntraSignInButton.tsx
frontend/src/auth/logic/redirectOauth.ts
frontend/src/pages/auth/signup.tsx

트센 요구사항에 따라 사용자가 이미지를 업로드하지 않으면 기본 이미지 등록
잘 들어가는거 확인함
796005815ea91db9ab64f007a7736989a635fe79
redirectOauth가 폴더 이동하고, redirect42Oauth로 바뀜
2604df97d2ebd7f22fa952eefdb164ca11b51d18
b4784738d02a4ee26f291c30e19ca14a10cc7f58
avatar는 empty()할 수 있어야함
https://github.com/pong-nyan/pong-nyan/pull/141/commits/fda428c77b835dde20059e20a4abd0d4132383e3

138 이미지 미등록시 기본 이미지 등록

---

frontend/src/auth/styles/SignUp.module.css
frontend/src/pages/auth/signup.tsx

137 회원가입쪽 ux개선

---

backend/src/auth/auth.controller.ts
backend/src/entity/User.ts
backend/src/rank/rank.service.ts
frontend/src/pages/rank/index.tsx
frontend/src/rank/components/RankUserList.tsx
frontend/src/type/rankType.ts

- 순위가 제대로 보이게 수정
- 뷰테이블을 사용함 
https://localhost/api/docs#/backdoor/AuthController_backdoor
mock 유저객체 만드는 백도어 뚫어둠

126 rankpage viewtable을 이용해서 리팩토링

---

backend/src/config/datasource.ts
backend/src/entity/Friend.ts
backend/src/entity/FriendStatus.ts

엔티티 추가만 했습니다. 알아서 잘 사용하시면 될 듯 합니다.

feat(backend): Friend 관련 entity 추가

---

backend/src/rank/rank.controller.ts
frontend/src/_components/FeatureLinkList.tsx
frontend/src/pages/index.tsx
frontend/src/styles/FeatureLinkList.module.css

120-프론트-메인-화면-구성

---

backend/src/app.module.ts
backend/src/rank/rank.module.ts
frontend/src/rank/components/RankUser.tsx
frontend/src/type/rankType.ts

rank쪽 타입 수정 및 import를 이상하게 하던거 수정

152 rank 쪽 타입 정리

---

frontend/src/friend/components/Manage.tsx
frontend/src/friend/components/PendingFriend.tsx
frontend/src/friend/components/PendingFriendList.tsx
frontend/src/friend/components/RequestFrien.tsx
frontend/src/friend/components/RequestFriend.tsx
frontend/src/friend/styles/Manage.module.css
frontend/src/friend/styles/PendingFriend.module.css
frontend/src/friend/styles/RequestFriend.module.css
frontend/src/pages/friend/manage.tsx
frontend/src/type/friendType.ts

155 친구관리 페이지 초안 만들기

---

frontend/src/chat/components/MessageList.tsx

feat(chat): 링크로 채팅창에서 profile로 보내기

---

backend/src/entity/Game.ts
backend/src/game/game.api.service.ts
backend/src/game/game.gateway.ts
backend/src/game/game.module.ts
backend/src/type/gameType.ts

게임이 끝난뒤 DB에 박을 수 있도록 메소드 구현
test는 필요함 -> 게임 종료 이벤트에서 직접 확인해봐야할듯 
-> 이후 gameInfo에 박히는 값들을 정한뒤에 `<Matching />` 컴포넌트에서 적절하게 보여주어야함. (현재는 그냥 JSON.striginfy해서 string으로 보여줌)

168 게임이 끝난뒤에 db에 업데이트할 때 사용할 메소드

---

backend/src/app.gateway.ts
backend/src/auth/google2fa.controller.ts
backend/src/auth/google2fa.gateway.ts
backend/src/type/userType.ts
backend/src/user.service.ts

제곧내
google2fagateway 에 있던 setIdMap, deleteIdMap 삭제했습니다.

소켓 연결되면 online true 소켓 끊기면 online false 로 변경

---

backend/src/game/game.gateway.ts
backend/src/type/userType.ts
frontend/src/context/socketGameEvent.ts
frontend/src/game/components/End.tsx
frontend/src/game/components/Run.tsx
frontend/src/game/components/RunWrapper.tsx
frontend/src/game/components/Start.tsx
frontend/src/game/matterEngine/matterJsGameEvent.ts
frontend/src/game/styles/End.module.css
frontend/src/pages/game/index.tsx
frontend/src/type/gameType.ts
frontend/src/type/userType.ts

- game 이제 5점 이상 넘어가면 끝남
https://github.com/pong-nyan/pong-nyan/assets/60354633/cf3e15af-6596-40f1-9ac8-2016600af034
https://github.com/pong-nyan/pong-nyan/assets/60354633/f1c8c546-ef55-4290-b00c-e513605cfd2f
- 5점 전까지는 game-score 이벤트 보냄
- 이후에는 game-end 보냄
- game bug 미해결

38 game end event 구현하기

---

backend/src/chat/chat.gateway.ts
backend/src/chat/chat.service.ts
backend/src/type/chatType.ts
frontend/src/chat/components/ChannelList.tsx
frontend/src/chat/components/ChatRoom.tsx
frontend/src/chat/utils/chatLocalStorage.ts
frontend/src/context/socket.ts
frontend/src/pages/chat/list.tsx

- 이전에 조금씩 이상하게 동기화가 안되던 문제들을 전부 해결했습니다.
- 새로고침할때 동기화안되던문제 해결
- maxUser
- Link로 href해놓고 안에 onClick줘서 생기던 각종문제해결

191 use maxuser

---

backend/package-lock.json
backend/package.json
backend/src/chat/chat.gateway.ts
frontend/package-lock.json
frontend/package.json
frontend/src/chat/components/ChannelList.tsx
frontend/src/chat/components/MakeChannel.tsx

121 채널 패스워드 저장시 hash후 저장

---

frontend/src/_components/FeatureLinkList.tsx

feat(frontend): add friend link

---

backend/src/friends/friends.service.ts
frontend/src/friends/components/Friend.tsx
frontend/src/friends/components/Friends.tsx
frontend/src/type/friendType.ts

210 친구 상태에 따라 이름 색깔 변하기

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.dto.ts
backend/src/auth/google2fa.controller.ts
backend/src/entity/User.ts
frontend/src/auth/components/Google2FA.tsx
frontend/src/auth/components/No2FA.tsx
frontend/src/auth/styles/No2FA.module.css
frontend/src/pages/auth/no-2fa-signin.tsx

213 2차 인증 선택

---

backend/src/app.module.ts
backend/src/auth/google2fa.gateway.ts
backend/src/chat/chat.gateway.ts
backend/src/game/game.gateway.ts
backend/src/user.service.ts
frontend/src/auth/components/Google2FA.tsx
frontend/src/context/socket.ts
frontend/src/context/socketGameEvent.ts
frontend/src/pages/_app.tsx

- auth namespace
- game namespace
- chat namespace

200 socket namespace 구현하기

---

backend/src/game/game.gateway.ts
frontend/src/chat/components/ChannelList.tsx
frontend/src/chat/components/ChatRoom.tsx
frontend/src/chat/components/MakeChannel.tsx

feat(chat): 새로운 채팅구조에 맞게 바꾸기

---

frontend/src/pages/profile/[nickname].tsx
frontend/src/profile/components/RequestFriendInProfile.tsx

feat: 친구의 프로필에서 친구요청가능하게

---

backend/src/game/game.gateway.ts
backend/src/game/game.service.ts
backend/src/user.service.ts
frontend/src/context/socket.ts
frontend/src/game/components/GameLoading.tsx

- game handle 처리
- socket 다르면 처리 해줌

223 game namespace socket 이용해서 disconnect 처리

---

frontend/src/context/socketGameEvent.ts
frontend/src/game/components/OriginPongRun.tsx
frontend/src/game/components/Run.tsx
frontend/src/game/components/RunWrapper.tsx

- 안 나간 상대방에게 1점을 추가로 주어서 승리하게 만듦

231 disconnection 시 승자 1 점 부여 후 승리

---

backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/profile/profile.controller.ts
backend/src/profile/profile.module.ts
backend/src/profile/profile.service.ts
backend/src/user.service.ts
frontend/src/context/usePostFetchData.ts
frontend/src/pages/auth/signup.tsx
frontend/src/profile/components/UpdateMyInfo.tsx

221 사용자들에게 잘못된 입력에 대해 알려주기

---

backend/src/chat/chat.gateway.ts
backend/src/chat/chat.service.ts
frontend/src/chat/components/ChannelList.tsx
frontend/src/chat/components/ChatRoom.tsx
frontend/src/chat/components/MakeChannel.tsx

- 비밀번호 변경
- 비밀번호 제거
- 권한임명후 버그 고침
- 관리자 제거 구현

226 비밀번호 변경제거

---

backend/src/chat/chat.gateway.ts
backend/src/chat/chat.service.ts
frontend/src/chat/components/ChatRoom.tsx

feat(chat): user Kick기능구현

---

backend/src/entity/Game.ts
backend/src/game/game.gateway.ts
backend/src/game/game.service.ts
backend/src/type/gameType.ts
backend/src/type/userType.ts
frontend/src/context/socketGameEvent.ts
frontend/src/friends/hooks/socketFriendEvent.ts
frontend/src/game/components/OriginPongRun.tsx
frontend/src/game/components/Start.tsx

177 게임 끝나면 db에 insert addgameinfo 메소드 사용

---

backend/src/game/game.gateway.ts
backend/src/game/game.service.ts
frontend/src/context/socketGameEvent.ts

244 게임이 정상적으로 끝날 수 있도록

---

backend/src/friends/friends.service.ts
frontend/src/friend/components/RequestFriend.tsx
frontend/src/profile/components/RequestFriendInProfile.tsx

feat(friend): 친구요청시 오류 적절하게 핸들링

---

frontend/src/game/components/Run.tsx
frontend/src/pages/profile/[nickname].tsx
frontend/src/profile/components/Matching.tsx
frontend/src/profile/components/Profile.tsx
frontend/src/profile/components/RecentGame.tsx
frontend/src/profile/styles/Profile.module.css
frontend/src/profile/styles/RecentGame.module.css
frontend/src/type/profileType.ts

252 프로필페이지 UI 개선작업

---

frontend/src/chat/components/ChannelList.tsx
frontend/src/chat/components/ChatRoom.tsx
frontend/src/chat/components/MakeChannel.tsx
frontend/src/friends/components/Friend.tsx
frontend/src/friends/components/Friends.tsx

feat: add: useAuth 추가

---

backend/src/friends/friends.controller.ts
backend/src/friends/friends.service.ts

feat: 이미 친구이면 친구요청 못하게

---

backend/src/game/game.service.ts
backend/src/type/gameType.ts

fix: 신청한 친구로만 친구매칭이 시작할 수있게

---

frontend/src/profile/components/Profile.tsx

- 프로필 닉네임이 업데이트시 페이지를 업데이트하게 수정

fix: useEffect를 통해 닉네임이 들어왔을 때 갱신하도록 수정

---

frontend/src/profile/components/RequestFriendInProfile.tsx

fix: 친구매칭으로 인한 게임 버그 fix

---

backend/src/chat/chat.gateway.ts
backend/src/chat/chat.service.ts
backend/src/type/chatType.ts
frontend/src/chat/components/ChannelList.tsx
frontend/src/chat/components/ChatRoom.tsx
frontend/src/type/chatType.ts

247 chat kick ban

---

frontend/src/game/components/Run.tsx
frontend/src/profile/styles/Profile.module.css

1. 프론트에서 5점 초과가 될 때 비정상 게임으로 게임 끝냄.
2. 프로필 css 수정

260 게임 뒤로가기 버그

---

backend/src/auth/google2fa.controller.ts
frontend/src/auth/components/No2FA.tsx
frontend/src/context/usePostFetchData.ts
frontend/src/friend/components/PendingFriend.tsx
frontend/src/friend/components/PendingFriendList.tsx
frontend/src/friend/components/RequestFriend.tsx
frontend/src/friends/hooks/useGetFriendsData.tsx
frontend/src/pages/chat/public-channel-list.tsx
frontend/src/pages/rank/index.tsx
frontend/src/profile/components/Profile.tsx
frontend/src/profile/components/RequestFriendInProfile.tsx
frontend/src/profile/components/UpdateMyInfo.tsx
frontend/src/profile/styles/Profile.module.css

237 localstorage에는 user 남아있고 pn jwt는 없을 때 적절하게 처리

---

frontend/src/pages/profile/[nickname].tsx
frontend/src/pages/profile/block.tsx
frontend/src/profile/components/Block.tsx
frontend/src/profile/components/RequesetBlock.tsx

feat: 유저block을 위한 프론트페이지 뼈대

---

backend/src/chat/chat.gateway.ts
frontend/src/chat/components/ChatRoom.tsx

269 mute구현

---

frontend/src/chat/components/ChatRoom.tsx

feat: 뒤로가기 버튼

---

backend/src/profile/profile.controller.ts
backend/src/profile/profile.dto.ts
backend/src/profile/profile.service.ts
frontend/src/profile/components/UpdateMyInfo.tsx

- 빈배열의 경우 : 2fa를 제외한 나머지 값은 자동으로 자기자신을 입력, email의 경우 you_must_input@email.com으로 입력 됨.

feat: profile 빈 값일 경우 값을 자동으로 넣어줌.

---

backend/src/game/game.service.ts

fix: ball이 나가면 가운데로 보정하게

---

backend/src/app.controller.ts
backend/src/chat/chat.gateway.ts
frontend/src/context/socketChatEvent.ts
frontend/src/profile/components/RequesetBlock.tsx

- block userList는 app controller에서 가져옴
- 프로필에서 유저차단 버튼을 누르면 block user List 업데이트 됨

feat(chat): block user 구현!
